/* Populate database with sample data. */

INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Agumon', DATE '2020-02-03', 0, true, 10.23);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Gabumon', DATE '2018-11-15', 2, true, 8);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Pikachu', DATE '2021-01-07', 1, false, 15.04);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Devimon', DATE '2017-05-12', 5, true, 11);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Charmander', DATE '2020-02-08', 0, false, 11);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Plantmon', DATE '2022-11-15', 2, true, 5.7);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Squirtle', DATE '1993-04-02', 3, false, 12.13);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Angemon', DATE '2005-06-12', 1, true, 45);
INSERT INTO animals(name, date_of_birth, escape_attempts, neutered, weight_kg)
values ('Blossom', DATE '1998-10-13', 3, true, 17);